<Project Sdk="Godot.NET.Sdk/4.7.2">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Game</AssemblyName>
    <RootNamespace>Root</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <PropertyGroup>
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug' Or '$(Configuration)' == 'Release'">
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputType>Exe</OutputType>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release' Or '$(Configuration)' == 'ExportRelease'">
    <DefineConstants>$(DefineConstants);ENSEMBLE_RELEASE</DefineConstants>
    <OptimizationPreference>Speed</OptimizationPreference>
    <PublishAot>true</PublishAot>
    <TrimMode>full</TrimMode>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug' Or '$(Configuration)' == 'ExportDebug'">
    <DefineConstants>$(DefineConstants);ENSEMBLE_DEBUG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'ExportDebug' Or '$(Configuration)' == 'ExportRelease'">
    <DefineConstants>$(DefineConstants);EXPORT</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <LaunchScriptExt>cmd</LaunchScriptExt>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <LaunchScriptExt>sh</LaunchScriptExt>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="$(TargetName)"/>
    <TrimmerRootAssembly Include="GodotSharp"/>
    <TrimmerRootDescriptor Include="TrimmerRoots.xml"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0"/>
    <PackageReference Include="Avalonia.Controls.WebView" Version="12.1.0"/>
    <PackageReference Include="Avalonia.Skia" Version="12.1.2" IncludeAssets="none"/>
    <PackageReference Include="Avalonia.Themes.Simple" Version="12.1.2"/>
    <PackageReference Include="Avalonia.Wayland" Version="12.1.2"/>
    <PackageReference Include="Avalonia.X11" Version="12.1.2"/>
    <PackageReference Include="AvaloniaEdit.TextMate" Version="12.0.0"/>
    <PackageReference Include="BogaNet.TTS" Version="1.4.0"/>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70"/>
    <PackageReference Include="Fonts.Avalonia.JetBrainsMono" Version="0.14.0"/>
    <PackageReference Include="Hardware.Info" Version="110.0.0.1"/>
    <PackageReference Include="LiveMarkdown.Avalonia" Version="2.4.0"/>
    <PackageReference Include="LiveMarkdown.Avalonia.Svg.Skia" Version="2.4.0"/>
    <PackageReference Include="LuaCSharp" Version="0.5.6"/>
    <PackageReference Include="MethodBoundaryAspect.Fody" Version="2.0.150"/>
    <PackageReference Include="Meziantou.Analyzer" Version="3.0.220">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11"/>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11"/>
    <PackageReference Include="Optris.LoadingIndicators.Avalonia" Version="12.0.4"/>
    <PackageReference Include="Serilog" Version="4.4.0"/>
    <PackageReference Include="Serilog.Expressions" Version="5.0.0"/>
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0"/>
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1"/>
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1"/>
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
    <PackageReference Include="ServiceScan.SourceGenerator" Version="3.2.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Threading.RateLimiting" Version="10.0.11"/>
    <PackageReference Include="TinyDialogsNet" Version="2.0.0"/>
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="AutoloadGenerator/AutoloadGenerator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"/>
    <ProjectReference Include="Core/Core.csproj"/>
    <ProjectReference Include="Estragonia/Estragonia.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Avalonia.Skia">
      <HintPath>Estragonia/Lib/Avalonia.Skia.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)LICENSE.md" CopyToPublishDirectory="PreserveNewest"/>
    <None Include="**/*.gd;**/*.gdshader;assets/**" Exclude=".godot/**;bin/**;**/*.import">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
    <None Include="Properties/**" Exclude="**/*.gdignore"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AutoloadGenerator/**"/>
    <Compile Remove="Core/**"/>
    <Compile Remove="Estragonia/**"/>

    <EmbeddedResource Remove="AutoloadGenerator/**"/>
    <EmbeddedResource Remove="Core/**"/>
    <EmbeddedResource Remove="Estragonia/**"/>
  </ItemGroup>

  <Target Name="GenerateBuildInfo" BeforeTargets="BeforeCompile">
    <PropertyGroup>
      <BuildTime>$([System.DateTime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ss UTC"))</BuildTime>
    </PropertyGroup>

    <ItemGroup>
      <BuildInfoLines Include="public static class BuildInfo"/>
      <BuildInfoLines Include="{"/>
      <BuildInfoLines Include="&#9;public const string BuildTime = &quot;$(BuildTime)&quot;%3B"/>
      <BuildInfoLines Include="}"/>
    </ItemGroup>

    <WriteLinesToFile File="$(IntermediateOutputPath)BuildInfo.g.cs" Lines="@(BuildInfoLines)" Overwrite="true"/>

    <ItemGroup>
      <Compile Include="$(IntermediateOutputPath)BuildInfo.g.cs"/>
    </ItemGroup>
  </Target>

  <Target Name="PrepareGodotExport" BeforeTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)/bin/linux"/>
    <MakeDir Directories="$(MSBuildProjectDirectory)/bin/windows"/>

    <WriteLinesToFile File="$(MSBuildProjectDirectory)/bin/.gdignore" Lines="" Overwrite="false"/>
  </Target>

</Project>
