<Project Sdk="Godot.NET.Sdk/4.7.0">
  <!-- TODO comments suffixed with a question mark are optional -->
  <PropertyGroup>
    <AssemblyName>Game</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisMode>Recommended</AnalysisMode>
    <RootNamespace>Root</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <!-- TODO: Enable NativeAot? May require updates to Lib/Estragonia, so it must wait -->
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <!-- Build an .exe file for the Avalonia UI designer -->
    <OutputType>Exe</OutputType>
    <UseAppHost>false</UseAppHost>
    <!-- Fix for a bug where the System.Threading.RateLimiting .dll file is not copied to the '/bin/' directory -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <!-- TODO: Explicitly define the 'PrivateAssets' tag for each package reference? I don't intend on using this proj as a dep -->
    <PackageReference Include="Avalonia.Themes.Simple" Version="[11.3.18]"/>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
    <PackageReference Include="Fonts.Avalonia.JetBrainsMono" Version="0.14.0"/>
    <PackageReference Include="MethodBoundaryAspect.Fody" Version="2.0.150"/>
    <PackageReference Include="Meziantou.Analyzer" Version="3.0.121">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="10.0.9"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.9"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.9"/>
    <PackageReference Include="Scrutor" Version="7.0.0"/>
    <PackageReference Include="System.Threading.RateLimiting" Version="10.0.9"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Lib\Estragonia\Estragonia.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <!-- Include GDScript source code files, but exclude those cached in the '/.godot/' directory -->
    <Content Include="**\*.gd" Exclude=".godot\**">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Remove="Lib\**"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Lib\**"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Lib\**"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="SessionManager\" />
  </ItemGroup>
</Project>
