name: Publish Release Binaries

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            godot: linux
            preset: Linux (x86_64)
            output: builds/linux-x86_64
          - os: windows-latest
            godot: windows
            preset: Windows (x86_64)
            output: builds/win-x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Godot
        shell: bash
        run: |
          mkdir godot
          cd godot

          if [ "${{ matrix.godot }}" = "linux" ]; then
            wget -q https://github.com/godotengine/godot-builds/releases/download/4.7.1-stable/Godot_v4.7.1-stable_mono_linux_x86_64.zip
            unzip -q Godot_v4.7.1-stable_mono_linux_x86_64.zip
            echo "$PWD" >> "$GITHUB_PATH"
          else
            wget -q https://github.com/godotengine/godot-builds/releases/download/4.7.1-stable/Godot_v4.7.1-stable_mono_win64.zip -O godot.zip
            unzip -q godot.zip
          fi

      - name: Install Export Templates
        shell: bash
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.7.1.stable.mono

          if [ "${{ matrix.godot }}" = "linux" ]; then
            wget -q https://github.com/godotengine/godot-builds/releases/download/4.7.1-stable/Godot_v4.7.1-stable_mono_export_templates.tpz -O templates.tpz
          else
            curl -L https://github.com/godotengine/godot-builds/releases/download/4.7.1-stable/Godot_v4.7.1-stable_mono_export_templates.tpz -o templates.tpz
          fi

          unzip -q templates.tpz -d ~/.local/share/godot/export_templates/4.7.1.stable.mono

      - name: Export
        shell: bash
        run: |
          if [ "${{ matrix.godot }}" = "linux" ]; then
            godot \
              --headless \
              --export-release "${{ matrix.preset }}"
          else
            ./godot/Godot_v4.7.1-stable_mono_win64.exe \
              --headless \
              --export-release "${{ matrix.preset }}"
          fi

      - if: runner.os == 'Linux'
        run: |
          cd ${{ matrix.output }}
          zip -r ../../Ensemble-${{ matrix.godot }}.zip .

      - if: runner.os == 'Windows'
        run: Compress-Archive -Path "${{ matrix.output }}\*" -DestinationPath Ensemble-${{ matrix.godot }}.zip

      - uses: actions/upload-artifact@v4
        with:
          name: Ensemble-${{ matrix.godot }}
          path: Ensemble-${{ matrix.godot }}.zip
