name: Upload Source Lines of Code

on:
  push:
    branches-ignore:
      - 'dependabot/**'

permissions:
  contents: read

concurrency:
  group: cloc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cloc:
    name: Count
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Count source LoC
        uses: djdefi/cloc-action@6
        with:
          options: --exclude-lang=YAML --md --report-file=cloc.md

      - name: Upload LoC artifact
        uses: actions/upload-artifact@v7
        with:
          name: source-loc
          path: cloc.md
          if-no-files-found: error
