name: Upload Source Lines of Code

on:
  push:
    branches-ignore:
      - 'dependabot/**'

permissions:
  contents: read

jobs:
  cloc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Count Source LoC
        uses: djdefi/cloc-action@6
        with:
          options: --exclude-lang=YAML --md --report-file=cloc.md

      - name: Upload LoC Artifact
        uses: actions/upload-artifact@v7
        with:
          name: source-loc
          path: cloc.md
          if-no-files-found: error
