on:
  push:
    branches:
      - master
      - test

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - run: rm -rf .git .github

      - uses: timo-reymann/deterministic-zip-gh-action@v1
        with:
          source: .
          target: src.zip
          args: -i

      - run: sha256sum src.zip

      - uses: actions/upload-artifact@v7
        with:
          name: src
          path: src.zip
