on:
  push:
    branches:
      - master
      - test

jobs:
  job:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - run: rm -rf .git .github

      - uses: timo-reymann/deterministic-zip-gh-action@v1
        with:
          source: .
          target: src.zip
          args: -i

      - run: sha256sum src.zip > src.zip.sha256

      - run: cat src.zip.sha256

      - run: |
          gh release create "${{ github.ref_name }}" \
            --generate-notes \
            src.zip \
            src.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
